### ISSUE TITLE
Mobile Nav Menu Hover/Selected Item behavior

### ISSUE THREAD

**Issue by Blackbaud-LoriWeiss** [blackbaud/skyux1#100]
Currently, in the mobile experience of RE NXT, when you open the nav menu, the user's current page is highlighted with white text and a green accent line.
![image](https://cloud.githubusercontent.com/assets/12037781/11543200/4bfe8cb8-9909-11e5-9f5f-5b96c47bdb66.png)

When a user clicks on a parent navigation item for a different area of RE NXT (ie: Clicking on Lists while in Fundraising), the item expands to show its children and appears to be in the selected state. The selected state is the same as the current page, white text and green accent line.
![image](https://cloud.githubusercontent.com/assets/12037781/11543186/3d85ffd6-9909-11e5-8fba-9ab30a3fb5a1.png)

We think this might be a confusing experience for the user, because multiple items in the navigation menu can appear to be selected.

**Comment by Blackbaud-LoriWeiss** [comment]
We recognize that this work will most likely need to be completed outside of Sky, but we were looking for Sky guidance on what the behavior /should/ be

**Comment by Blackbaud-ToddRoberts** [comment]
It looks right on my phone:
![wp_ss_20151217_0001](https://cloud.githubusercontent.com/assets/13765813/11872857/96e12982-a4a5-11e5-8b59-aff493a39ec8.jpg)

I assume this is an artifact of testing at browser resolution on a desktop, because it is true that the links will turn white when you mouse over them. However, AFAIK this will not happen on a phone. We could turn off the hover selector for mobile resolutions only but I don't know if we want the complexity of doing that if the problem won't show up in the wild. Plus if someone is viewing at mobile resolution on a desktop, the expectation would be to see the hover effect anyway.

**Comment by Blackbaud-JonathanBell** [comment]
Hey Todd,  Lori is switching teams so I'll chime in on this issue.     

You are correct in the difference you are seeing is a result of using a scaled-down browser instead of a mobile device.  When you click on something in mobile, it activates hover and maintains hover until you click on something else, so you experience what Lori showed.   Also, RENXT.Blackbaud.com is behaving this way for desktop as well but now it is truly just a hover in CDEV so that is some improvement.

I agree that we don't want to get too hacky for mobile and negatively affect the desktop experience.  We talked this over with Paul Crowder a while back and one possible recommendation we had was for the hover color (brightness?) to be slightly different than the selected version so there is a distinction between hover state and selected state.  That would be applied to desktop nav bar as well as mobile.  Just a thought.  We were handing it over to you guys to think more about and come to the bottom of, but right now it is a strange experience on a mobile device.

**Comment by Blackbaud-PatrickOFriel** [comment]
@Blackbaud-NickQuagliara, is this being redone in your nav design updates?

**Comment by Blackbaud-PatrickOFriel** [comment]
Closing this as design is reworking mobile nav as a whole and that should be on our docket by the end of February
