### ISSUE TITLE
UI Select: Dropdown list has a direction up in Chrome

### ISSUE THREAD

**Issue by Blackbaud-PatrickOFriel** [blackbaud/skyux1#102]
From @Blackbaud-ScottKavanagh

This appears to be only happening with Google Chrome and I believe its related the following select control bug. angular-ui/ui-select#977
When I position the tile as a tile on the first row of our constituent page the dropdown is correctly rendering in the down position

**Comment by Blackbaud-PatrickOFriel** [comment]
@Blackbaud-ScottKavanagh is this still an issue with you? and what version is your angular-ui-select on because sky is on 0.11.2 and I do not believe there is support for placing the dropdown in the up position in that version

**Comment by Blackbaud-ScottKavanagh** [comment]
Shell is on 0.11.2 which is the version we'd be using.  I can't easily say if this is still occurring or not just because we ended up avoiding the UI multi-select control on our form due this bug and others we were seeing at the time.  I can try find some time to stage it again, but it looks likely the update fixed this.  At the very least there looks like there is now a way to force the dropdown to be in the down direction.

**Comment by Blackbaud-PatrickOFriel** [comment]
It looks like ui-select started supporting dropdown direction changing to up in 0.12.0 https://github.com/angular-ui/ui-select/commit/02bebc0d48b0faf81a62bac3f0eb1f855db1f7dc. Maybe y'all were bringing it in separately from sky at some point but since now you're on 0.11.2 this should not be an issue, so I'm going to close it.
