### ISSUE TITLE
NPM + Bower Disaster Recovery

### ISSUE THREAD

**Issue by Blackbaud-PatrickOFriel** [blackbaud/skyux1#103]
Prepare for a day when we need to build / release and one following are true:

NPM is down
NPM package removed from registry
Bower is down
Bower package removed from registry
Our initial thoughts are to have Travis commit the bower_components and node_modules folder into a different repo.

An update. We've enabled Travis' built in caching support for the node_modules, bower_components, and SlimerJS temp install folders. This is a good first step, but still has a few limitations.

npm install is still ran
No way to download the caches, just delete them via Travis
Going forward, we should look at a solution like the one Bootstrap uses or one described in  [this article](http://hgc.io/2014/08/26/Caching-Travis-CI-dependencies-in-S3/).

**Comment by Blackbaud-RobertTester** [comment]
Hey Patrick, have you thought about having a NPM and Bower Proxy?  We are in the process of setting those up so when we do a bower install or a npm install we would look to our proxy for dependencies instead of going to the public registry.

**Comment by Blackbaud-BobbyEarl** [comment]
@Blackbaud-RobertTester Are you all setting up private registries?

**Comment by Blackbaud-RobertTester** [comment]
Yes we are.  We had a lot of problems pulling down npm and bower dependencies during our build process so we are going to move forward with private registries.  This would eliminate any problem you would have with reaching the public bower or npm registries.  

Initially they will just cache the public registries but overtime we plan on publishing our own libraries to them.

**Comment by Blackbaud-BobbyEarl** [comment]
That makes sense.  We haven't had the same problem pulling our dependencies.  Putting in a proxy registry seems like additional steps for a problem we haven't seen.  We're more focused on being able to replicate any build Travis does.  I think we're still going to focus on storing the `node_modules` and `bower_components` folders after a successful build.

Thanks for the suggestion though.  I am interested in your implementation, so feel free to keep us in the loop with how it goes.

**Comment by Blackbaud-BobbyEarl** [comment]
The article originally mentioned using the built-in caching from Travis CI.  It wasn't originally available for Open Source repos, which is why the article describes an alternative.  Now that it is available (and we're using it correctly #390), using the article as an example isn't relevant.

Having said that, although we were trying to be proactive, we just haven't met the doomsday scenario described.  We could possible store the `node_modules` / `bower_components` folders on every build (or a map as they rarely change), but at roughly 50MB, we would very quickly amass a large repo or bucket.

Similarly, we could implement a private registry to rely on it's proxying capabilities.  I'm interested to see if @Blackbaud-RobertTester had any luck with such a mechanism?

Until actually warranted, instead of over-preparing, I'm closing this pull request.

**Comment by Blackbaud-RobertTester** [comment]
@Blackbaud-BobbyEarl : We have setup a private npm proxy that we are using for LO.  I don't think we can publish it publicly.  However, if you guys wanted to use it for your build we could probably set that up.  Just let me know.

Something else to note is we started checking in our bower_components directory to avoid bugs with transitive dependency updates.  We ran into a scenario where a 1.1.x upgrade broke our app :-).
