### ISSUE TITLE
Add left padding to nav-tabs class

### ISSUE THREAD

**Issue by Blackbaud-RobertTester** [blackbaud/skyux1#137]
Should the SkyUX controls follow the patterns that are UX teams are coming up?  For example, the tabs controls are all left aligned.  However, the UX team says that there should be an indentation on the tabs.  Also, the tabs have this indentation in renxt through sky.css but not by default.  I think it should have this css by default when you use the directive.  Thoughts?

**Comment by Blackbaud-PatrickOFriel** [comment]
Our demos should follow the sky UX patterns. I agree that the padding should be there by default if tabs should always have that 15px of padding to the left. @Blackbaud-ToddRoberts is there any case where that left padding for the tabs should not be there?

And thanks for catching this @Blackbaud-RobertTester, if you see anymore items in the component demos that don't follow the patterns, keep the issues coming because we need to take care of them.

**Comment by Blackbaud-ToddRoberts** [comment]
As far as I know tabs should always have that padding.

Is the question here whether the directive itself should contain the CSS so as to render properly if sky.css is not being used?

**Comment by Blackbaud-RobertTester** [comment]
The tab only renders correctly when using css that is specific to the renxt UI.  There is a rule on one of the parent containers to do the indentation of the tabs.  I think it would be better to not assume a specific DOM hierarchy and just put the indentation on the control itself.

**Comment by Blackbaud-PatrickOFriel** [comment]
Yeah Todd if that's the case then I'm just going to add the padding directly to the `nav-tabs` class so anyone using the `tabset` directive gets the padding

**Comment by Blackbaud-PatrickOFriel** [comment]
In [v1.4.7](https://github.com/blackbaud/skyux/releases/tag/v1.4.7)
