### ISSUE TITLE
Grid component sort example code is reversed

### ISSUE THREAD

**Issue by Blackbaud-IsaacAggrey** [blackbaud/skyux1#177]
Expected behavior:
- ▲ is ascending - meaning that from the top to the bottom of the list the values become **bigger**
- ▼ is descending - meaning that from the top to the bottom of the list of values become **smaller**

Currently, the opposite occurs (e.g., sort by date) and this happened to cause confusion for my team as we followed the example code*: http://plnkr.co/edit/NDKXqRP6FuBwvKjbZyPD?p=preview

I've started a branch locally and made a Plunkr that demonstrates correct behavior (toggle the `Date` column): http://plnkr.co/edit/wTEGWzWzn3CjjLmRGWrs?p=preview

See this UX StackExchange discussion for further explanation of rationale: http://ux.stackexchange.com/questions/37564/use-up-or-down-arrow-to-represent-sort-ascending-at-table-header

I'll open a PR shortly to ask further questions about what else is necessary to contribute.

*on another note, why do users need to provide a sort function? It's general enough to just be included within the component instead of requiring all users to copy it across every grid's controller.

**Comment by Blackbaud-PatrickOFriel** [comment]
Thanks, Isaac, you're absolutely right. The reason users need to provide a sort function is that we can't assume that the data that users have loaded locally is all the data available, that is, in the sort function, the user may call out to a server to do the sorting. We have an open issue to give bb-grid and other directives an option to use a local search provided by sky #150. I'll add sort to that as well because that kind of goes hand in hand

**Comment by Blackbaud-PatrickOFriel** [comment]
Went ahead and fixed the demo in master, should be on the documentation site in the next release
