### ISSUE TITLE
Tile collapsed/expanded state not correct (Firefox)

### ISSUE THREAD

**Issue by Blackbaud-MichaelLopez** [blackbaud/skyux1#359]
### Expected behavior

Tile should be collapsed if actually collapsed and expanded if actually expanded.
### Actual behavior

We are seeing an issue where during the loading of a tile, the tile can't seem to determine whether it is collapsed or expanded.

Examples:

![tile-opened](https://cloud.githubusercontent.com/assets/11994579/13293506/edb68490-daed-11e5-9eee-a46baddacdd9.png)

You can see the tile is expanded, but the the caret is pointing in the wrong direction.

![tile-collapsed](https://cloud.githubusercontent.com/assets/11994579/13293575/26edd8da-daee-11e5-93fe-9306932469a9.png)

Similarly this tile is collapsed but the number doesn't show in the header. 

A odd thing I saw was was that the tile section node had both classes "collapsed collapsible" when its only supposed to have 1 of those at a time. This is causing styling breaks.

**Related issue: Tile doesn't expand/collapse when clicked**

The code here looks suspect:

`if (collapsed && !tileInitialized) {`
    `//in some cases the tile-content div is left in a partially collapsed state.`
    `//   this will ensure that the tile is styled corretly and the tile is completely collapsed'`
    `$timeout(function () {`
    `var contentEl;`
    `contentEl = el.find('.bb-tile-content');`
    `contentEl.removeClass('collapsing').addClass('collapse');`
    `}, 1);`
`}`

I believe this is breaking the angular ui bootsrap collapse directive by putting a class on the element that the directive is tracking internally.

Clicking on the tiles usually results in odd behavior the tile doesn't collapse, or it doesn't expand which would make sense since angular ui bootstrap doesn't know the correct state. They short circuit logic if the certain classes are present, in this case the collapse class.
### Steps to reproduce

random behavior, not easily reproducible 
### Plunker

No plunker because random

**Comment by Blackbaud-PatrickOFriel** [comment]
Yeah, that line seems strange, looks like it's relying on internal details of uib-collapse (which is a bad thing). I took a look at the proposal page and I'll investigate. It might be that with the upgrades to ui-bootstrap, that line of code isn't needed anymore and just messes stuff up.

**Comment by Blackbaud-PatrickOFriel** [comment]
Took a look at this. The version of ui-bootstrap that we upgraded to last month had some animation updates that made those lines of code you pointed out unnecessary and most likely caused the problems you're seeing. The changes to tiles are in master and we'll release at some point this week. You can test out CDEV with what's currently in master by adding `&sky=dev` to the end of the CDEV url

**Comment by Blackbaud-PatrickOFriel** [comment]
Hokay, reopened because this is still happening. Finally created a more minimal test case here: http://plnkr.co/edit/6b5WFYQQR9AH9y2yV1LH?p=preview, which should help us out (view the example with the dashboard wide enough for two columns of tiles). Also, pinpointed the reason that the tile that should be collapsed is still open. On the div with the `uib-collapse` directive, it has the classes `collapse` and `in` applied to it. `in` is a class used for animation, and it sets the display to block instead of none. It looks like the problem here is that in some cases, the `in` class is never removed when animation finishes. I'll dig a little deeper and see if I can find a solution (another text case that can be used try stuff locally http://plnkr.co/edit/2QokAHxgXnvTP9qJZ9u1?p=preview)

**Comment by Blackbaud-PatrickOFriel** [comment]
In [v1.5.10](https://github.com/blackbaud/skyux/releases/tag/v1.5.10)
