### ISSUE TITLE
New filtering options for Checklist

### ISSUE THREAD

**Issue by Blackbaud-ToddRoberts** [blackbaud/skyux1#470]
https://blackbaudinc.box.com/s/cj622hpepgf2bv7s4ufiqbmqc73j7jvz 

Designer: Todd 

Approved

**Comment by Blackbaud-PaulCrowder** [comment]
Possible implementation:
- Add `bb-checklist-subset-label` to enable the subset checkbox.  This label will be displayed next to the checkbox
- Add `bb-checklist-subset-property` so that local filtering can filter on the specified property.
- Add `subsetSelected` property to the filter callback object so the flag can be used for remote filtering.

**Comment by Blackbaud-PatrickOFriel** [comment]
Category select field and subset checkbox in [v1.5.18](https://github.com/blackbaud/skyux/releases/tag/v1.5.18)

**Comment by Blackbaud-PatrickOFriel** [comment]
Show only selected in [v1.5.20](https://github.com/blackbaud/skyux/releases/tag/v1.5.20)
