### ISSUE TITLE
Pagination min-height not correctly calculated in certain cases

### ISSUE THREAD

**Issue by Blackbaud-MichaelLopez** [blackbaud/skyux1#530]
### Expected behavior

Height is calculated correctly
### Actual behavior

Height is not calculated correctly
### Steps to reproduce

When a parent has a width, this is not taken into consideration during the height calculation. This causes an incorrect min height to be put on the pagination list.
### Plunker

http://plnkr.co/edit/FzWHjyPaXqmeEva5xDBf?p=preview

**Comment by Blackbaud-MichaelLopez** [comment]
I'm wondering if there is any UX work to be done here. I feel like calculating the min height is not the most robust solution as there are a bunch of problems that come into play (parent style rules, hidden elements, etc.). Might be better off having users define a min height and then allowing a scrollbar so the pagination numbers do not bounce around.

**Comment by Blackbaud-PatrickOFriel** [comment]
In [v1.6.2](https://github.com/blackbaud/skyux/releases/tag/v1.6.2)
We decided to just revert the moving offscreen behavior, since there was the workaround of using `ng-if` instead of `ng-show` for dealing with hidden pagination components. We don't really see having a scrollbar'ed area around the pagination content as ideal either. Really, you should probably just use the `uib-pagination` directive and not worry about the content being different heights, because users aren't likely to be rapidly paging through the content except in a demo situation.
