### ISSUE TITLE
Dropdown Menu Links: Too much padding

### ISSUE THREAD

**Issue by Blackbaud-SteveBrush** [blackbaud/skyux1#532]
Dropdown menu items have too much vertical padding. These links need to have smaller top and bottom padding, especially for longer dropdowns.

Here's the culprit:
https://github.com/blackbaud/skyux/blob/master/scss/_navigation.scss#L61

Ideally, the CSS would include the "child-of" operator (>), so that the styles are not passed down the chain indefinitely.

<img width="364" alt="screen shot 2016-04-26 at 10 46 27 am" src="https://cloud.githubusercontent.com/assets/12497062/14822357/5da65a30-0b9c-11e6-97a3-a843953b8833.png">

**Comment by Blackbaud-PatrickOFriel** [comment]
So, the idea of "too much" padding seems kind of amorphous. The issue here seems to be that you have a dropdown with a bunch of entries. Reducing the amount of padding seems to just mask the problem until you add more entries and the dropdown gets too long again. It might be better to solve the problem by adding a class in SkyUX that adds a max-height to the dropdowns and makes the dropdown scrollable.

What do you think @Blackbaud-ToddRoberts, @Blackbaud-PaulCrowder, @Blackbaud-BobbyEarl ?

**Comment by Blackbaud-ToddRoberts** [comment]
I can see updating nav items to have 44px vertical based on proposed touch target sizes. Right now it looks like they are 53. That doesn't solve the issue of long lists of items but I'd see that as something to solve by looking at the information architecture rather than the UI.

**Comment by Blackbaud-PatrickOFriel** [comment]
True enough, it might be that you just don't use extraordinarily long dropdowns, instead segment your information to have the main topics in a dropdown in the navbar and link to other pages elsewhere.

**Comment by Blackbaud-SteveBrush** [comment]
I agree about the long menu items, but visually speaking, the padding between items is definitely too much. Look at Bootstrap's defaults, as an example:

<img width="407" alt="screen shot 2016-04-26 at 4 04 39 pm" src="https://cloud.githubusercontent.com/assets/12497062/14832500/9f7b941c-0bc8-11e6-89c4-8557bd8aaebd.png">

**Comment by Blackbaud-PatrickOFriel** [comment]
We use Bootstrap as a base, but we don't accept all default styling as gospel. Just because Bootstrap has certain padding does not mean that SkyUX must have the same padding. That being said, Todd did say that we can reduce the vertical area for a dropdown item to 44px. We don't want to go below that because the touch target gets too small in mobile.

**Comment by Blackbaud-SteveBrush** [comment]
Cool, thanks all.

**Comment by Blackbaud-BobbyEarl** [comment]
Our `bb-context-menu` is using the same Bootstrap classes, but we don't override them like when do when implemented in a `navbar`.  I don't see a reason that these should be different.

To me, that means we either undo the padding override currently set on navbar items and let Bootstrap defaults take back over, or we also apply our override (even if we reduce it as @Blackbaud-ToddRoberts suggests) to `bb-context-menu` items.

I like the former, but if we are worried about touch target sizes, could we only apply that at smaller breakpoints?

**Comment by Blackbaud-PatrickOFriel** [comment]
We'll talk about it at next planning and see how design wants to approach this

**Comment by Blackbaud-PatrickOFriel** [comment]
Talked to Todd about this, and we decided that the navbar item height can come down to the correct touch-target size (44px). In the future, dropdown items will probably also come up to this height, but we're not going to do both at once

**Comment by Blackbaud-PatrickOFriel** [comment]
In [v1.5.21](https://github.com/blackbaud/skyux/releases/tag/v1.5.21)
