### ISSUE TITLE
multiple bbAutonumeric inputs cause infinite selecting

### ISSUE THREAD

**Issue by Blackbaud-MichaelLopez** [blackbaud/skyux1#64]
http://plnkr.co/edit/wOqxfxTaV3rt8WqDmQnd?p=preview

Focus the first bbAutonumeric input element, then focus the address bar of the browser, then focus the second bbAutonumeric input element. Notice infinite selecting.

**Comment by Blackbaud-PaulCrowder** [comment]
The culprit is [this code](https://github.com/blackbaud/skyux/blob/master/js/sky/src/autonumeric/autonumeric.js#L132-L141) where we select the text on focus inside a `$timeout`.  What happens is when the user clicks onto the second field, the originally-focused field's `focusin` event fires, then the clicked field's `focusin` fires.  Since the text selection happens in a timeout, the first field's text is selected after the second field has received focus, then the second field's text is selected after the first field receives focus, causing the endless loop.  This can be fixed by ensuring the field whose text is being selected actually has focus before selection occurs.
