### ISSUE TITLE
Select field component > "Clear selection" clears current field value instead of current modal selection

### ISSUE THREAD

**Issue by Blackbaud-TimothyWittig** [blackbaud/skyux1#673]
### Expected behavior

The "Clear selection" button of a select-field's  "Select value" modal should clear the selected value in the modal.
### Actual behavior

The "Clear selection" button of select-field's "Select value" modal dismisses the modal and clears out the select-field's current value.
### Steps to reproduce
1. Navigate to the provided plunker.
2. Observe that the "Single-select mode" value is currently set to "Soft credits"
3. Click on the select field to launch the "Select value" modal.
4. Click on the "Clear selection" button.
5. Observe that the modal has been dismissed and the "Single-select mode" value is no longer set to "Soft credits".
### Plunker

http://plnkr.co/edit/r6LrwKPTl9QkXK5LiAes?p=preview

**Comment by Blackbaud-ToddRoberts** [comment]
This is the intended behavior. Since selecting a different value will immediate close the field with that new value selected (i.e. you don't need to clear the selected row and then pick a new one) there is no reason to clear the value in the modal unless you are intending to clear out the field itself. We will be adding the ability to clear the selected value without opening the modal.

**Comment by Blackbaud-PatrickOFriel** [comment]
Is there any design around the actual button we need to change? Like the color or something to indicate that you're about to do some thing "close-y"

**Comment by Blackbaud-ToddRoberts** [comment]
Maybe could style it as a link button so it is ~ like cancel
