### ISSUE TITLE
bb-grid search field - Line between search text and magnifying glass visible on phone/ipad

### ISSUE THREAD

**Issue by Blackbaud-ChristiSchneider** [blackbaud/skyux1#721]
### Expected behavior

No artifacts in search field.
### Actual behavior

When searching on a phone or iPad, there is a pixel line that is visible between the search text and magnifying glass. It's more visible on the phone than the iPad and is noticeable because the line goes through the blue glow of the search field. 
I zoomed in on my desktop link but could not see it there. Also verified I could dupe on the phone with Safari and Chrome.
### Steps to reproduce
1. Access [http://skyux.developer.blackbaud.com/components/grids/](Grid docs page) on an iPhone
2. Scroll to demo "Grid with pagination in tile"
3. See that a 1 pixel line is visible to the left of the magnifying glass on the search box
4. Click the search box and the line becomes more visible

![2016-07-25 11 58 27](https://cloud.githubusercontent.com/assets/13154536/17108024/b802057e-525f-11e6-8d37-109994c6875f.png)
### Notes

Originally filed by Leslie Staggs, [TFS WI 653540](https://tfs.blackbaud.com/tfs/DefaultCollection/Products/_workitems?_a=edit&id=653540).

**Comment by Blackbaud-PatrickOFriel** [comment]
This bb-grid searchbox is kind of hacky in the way that it was put together. We have created the standalone search component here http://skyux.developer.blackbaud.com/components/search/ that doesn't have the visual artifacts that you see here and has the ability to be responsive on mobile devices. We have a story at #743 which will allow bb-grid to opt-in to the new search input (while not breaking backwards compatibility with the old search input). I will close this issue because we will just instruct users to use the new search component when the time comes.
