### ISSUE TITLE
Evaluate Coverity for security scans

### ISSUE THREAD

**Issue by Blackbaud-PatrickOFriel** [blackbaud/skyux1#80]
We need to scan our codebase periodically for security vulnerabilities. Coverity offers integrations with GitHub and Tavis CI, so we should be able to use them. T

https://scan.coverity.com/travis_ci

**Comment by Blackbaud-PatrickOFriel** [comment]
We might also want to look into Veracode, as apparently Blackbaud (and Bryan Z) have experience/some automated scripts using it

**Comment by Blackbaud-PaulCrowder** [comment]
After speaking with representatives at Coverity there is not a lot of analysis of client-side JavaScript code that would be valuable for Sky UX since their scans typically look for server-side vulnerabilities.  The primary client-side risk is HTML injection, and a lot of the technologies used by Sky UX (jQuery, Angular, etc.) by their very nature do a lot to mitigate the risk of HTML injection. I'm closing this issue until we can find a more compelling reason to look into it further.
