### ISSUE TITLE
File drop fails bootlint

### ISSUE THREAD

**Issue by Blackbaud-DanielCooke** [blackbaud/skyux1#812]
The following error occurs when running bootlint against items that utilize the file drop (noticed when using the avatar component).

bootlint:  E003  Found one or more `.row`s that were not children of a grid column or descendants of a `.container` or `.container-fluid`
 [div.row.bb-file-drop-row, prevObject: jQuery.fn.init[1], context: document]

-Use the sample avatar plunker (http://skyux.developer.blackbaud.com/components/avatar/).
-Make sure to open the live view in a new window (in the live view window, top right blue x button).  I think something with plunker's layout is causing a false negative on the linter.

Run the following command in the developer tools console
javascript:(function(){var s=document.createElement("script");s.onload=function(){bootlint.showLintReportForCurrentDocument([]);};s.src="https://maxcdn.bootstrapcdn.com/bootlint/latest/bootlint.min.js";document.body.appendChild(s)})();

**Comment by Blackbaud-PatrickOFriel** [comment]
The reason for this is because we assume you are placing this component in a bootstrap container  or container-fluid(which most (all) pages should be). We cannot include the container class as part of the file drop component because you cannot have a container within a container. Any of our components that have the bootstrap responsive column classes would have this behavior
