### ISSUE TITLE
bb-datepicker can't handle date time values with time component

### ISSUE THREAD

**Issue by Blackbaud-TimothyWittig** [blackbaud/skyux1#884]
### Expected behavior

I should be able to assign a javascript date time object that has a non-zero time component to a bb-datepicker's model.
### Actual behavior

Assigning a javascript date time object that has a non-zero time component to a bb-datepicker's model results in a "Please enter a valid date" error message.
### Steps to reproduce
1. Navigate to the plunker off of the datepicker component page: http://skyux.developer.blackbaud.com/components/datepicker/
2. In index.js, change the value of  `self.date2 = '2015-05-17T00:00:00';` to `self.date2 = '2016-10-19T00:00:01';`
3. Observe the validation error that now occurs.
### Plunker

http://plnkr.co/edit/bkK02xFQKjwBsJ8rfvvh?p=preview

**Comment by Blackbaud-PatrickOFriel** [comment]
Note that you are not passing a date time object, you are passing a date string. Currently it only accepts strings of that form in YYYY-MM-DDT00:00:00 format. And it strips the time out entirely and ignores it which might not even be the correct behavior if you're actually trying to pass a valid UTC offset. This was apparently done originally in RENXT to deal with SQL UTC Date strings. Do you know what the expected behavior in RENXT for this is for this format? Just stripping the time out if it's in string form, or actually adhering to the offset? I know RE7 dates can be stored in strange non-consistent ways

**Comment by Blackbaud-TimothyWittig** [comment]
Whoops you're right -- that is an ISO 8601 date string. My expectation with an ISO 8601 date string would be the following:
1. If there's no offset on the date string (no "-", "+", or "Z"), then the time component doesn't matter since we're only displaying a date. Therefore strip off the time component and assign from the date component.
2. If there is an offset on the date string ("-", "+", or "Z"), then the time component can matter if after converting to client's offset we're in another day. Therefore convert to client's offset and then assign from the date component.

**Comment by Blackbaud-PatrickOFriel** [comment]
In [v1.9.0](https://github.com/blackbaud/skyux/releases/tag/v1.9.0)
