### ISSUE TITLE
vertical tabs

### ISSUE THREAD

**Issue by Blackbaud-ToddRoberts** [blackbaud/skyux1#899]
https://blackbaudinc.box.com/s/4a6jg0ci2gzvish15aulmujntqnt3nwr 
Approved 
Designer: Tim

**Comment by Blackbaud-BenCook** [comment]
I am starting work on a PR for this since I have some extra time on my hands. No telling how long that will last, so I can't make any promises in terms of a timeline.

**Comment by Blackbaud-PatrickOFriel** [comment]
@Blackbaud-ToddRoberts is this any different from the sectioned form component that @Blackbaud-DanielCooke and @Blackbaud-MatthewBell contributed the past few weeks http://skyux.developer.blackbaud.com/components/sectionedform/

**Comment by Blackbaud-PatrickOFriel** [comment]
Oops, nevermind, read through the spec saw that vertical tabs are a separate thing. @Blackbaud-BenCook a bunch of styles are probably shared between the two though so that might be a good place to start looking

**Comment by Blackbaud-BenCook** [comment]
@Blackbaud-PatrickOFriel, thanks for the tip. They do have a lot of visual similarities. Question for the Sky team: do you see this as a new, stand-alone component or as something that could be enabled through a series of additional attributes on tabsets and tabs?

**Comment by Blackbaud-PatrickOFriel** [comment]
So ideally, this would be a series of additional attributes on tabsets and tabs. the problem is that we use the ui bootstrap tabs so it'll probably be difficult to get the collapsible vertical tab sections working around that. It might be unavoidable to create your own component.

**Comment by Blackbaud-ToddRoberts** [comment]
For styling please check with @Blackbaud-TimHammond and @Blackbaud-Robfavre since some questions came up about styling on sectioned forms, they will be the source of truth for which differences are intentional.

**Comment by Blackbaud-BenCook** [comment]
@Blackbaud-PatrickOFriel, I believe I can implement this through new attributes augmenting `uib-tabset`, but the real question is, if I do it this way, will it count as contributing a new component for the purposes of Lego minifigure-ization.

**Comment by Blackbaud-PatrickOFriel** [comment]
Hey, if you can get it working correctly, we'll be happy to give you a lego minifigure out of it.

**Comment by Blackbaud-BenCook** [comment]
@Blackbaud-TimHammond, @Blackbaud-Robfavre and @Blackbaud-ToddRoberts, is the mobile/tablet version of the component [here](https://blackbaudinc.app.box.com/s/4a6jg0ci2gzvish15aulmujntqnt3nwr) the definitive one (as opposed to [here](http://pgxisb.axshare.com/))? If so, I have a question about this part:

> Once a user drills into a tab, the contents load, and a button is placed in the toolbar that will allow users to go back to the list of tabs.  The text of this button can be configured by the developer.

Is the button that gets placed in the toolbar a part of the component itself or would it be enough to just provide a hook to open the tabs via a button supplied by the consuming page? It seems like it would be a problem where the vertical tabs occur on a page without a toolbar (e.g., the FE NXT settings page).

**Comment by Blackbaud-TimHammond** [comment]
You're looking at the right place.  There will always need to be a way for a user on a mobile device to get back to the tabs list, so the most important thing would be to make sure that everyone is able to take advantage of that functionality.  I worry that only providing a hook isn't prescriptive enough and that someone would overlook it.

**Comment by Blackbaud-BenCook** [comment]
I'm getting close to having a PR ready. In addition to needing visual regression tests and baseline screenshots, I still have some questions around mobile style/functionality. The main issue I see with providing a button in the tab content area to show/hide the tabs is that the tabset will have to insert the button either at the very top or very bottom of the transcluded tab content. There is no way to put the button in, say, an action bar because the tabset component has no knowledge of what is displayed in the content area.

Given this, these are some of the alternatives I see:
* Following the sectioned form, we could provide a hook, such as [an event that forces the component to reinitialize](https://github.com/blackbaud/skyux/blob/1e12f88c201c1b463335ec926b9bd06f6f057576/js/sky/src/sectionedform/sectionedform.component.js#L129), making the tabs visible. Client code would be responsible for [calling the hook](https://github.com/blackbaud/skyux/blob/1e12f88c201c1b463335ec926b9bd06f6f057576/js/sky/src/sectionedform/docs/demo.js#L51).
* Same as the previous, but we provide an optional directive that client code can put into their tab content that creates a button to call the provided hook. (Basically, this just makes implementation slightly easier.)
* We insert the button at the bottom of the content area in a fixed or absolutely positioned container that would always appear above any transcluded content. The button could be a small caret in the top-left or top-right of the screen or something like that.
* Allow users to swipe in the content area to return to the tabs. I'm not sure if some sort of visual indication would be needed to tell users to do this.

There definitely may be other options I'm not thinking of. What do y'all think?

**Comment by Blackbaud-ToddRoberts** [comment]
@Blackbaud-TimHammond can you take a look at these options?

**Comment by Blackbaud-PatrickOFriel** [comment]
From an engineering standpoint, I think we should follow how sectioned form works for consistency's sake, providing a hook to the component

**Comment by Blackbaud-TimHammond** [comment]
I agree with @Blackbaud-PatrickOFriel that providing hooks like we do for sectioned forms is ideal for consistency.  Also, it sounds like that option will be closest to the design that was approved.

**Comment by Blackbaud-BenCook** [comment]
Okay, cool, I'll adhere closely to the pattern set by the sectioned form component.

**Comment by Blackbaud-PatrickOFriel** [comment]
In [v1.15.0](https://github.com/blackbaud/skyux/releases/tag/v1.15.0)
