### ISSUE TITLE
Increase/make configurable the maxExpandedNewlines value in bb-textexpand

### ISSUE THREAD

**Issue by Blackbaud-DanMiller** [blackbaud/skyux1#91]
RE NXT clients are copying and pasting emails in actions. Some of these emails are chains and can become quite long. Once they reach a certain length, the logic around maxExpandedNewlines prevents the text from being formatted correctly in the expanded view. It would be beneficial to increase or allow us to configure that value.

**50 Newlines**
Collapsed
![image](https://cloud.githubusercontent.com/assets/11977741/11482437/c3772a74-9770-11e5-92df-27bd94481faf.png)

Expanded
![image](https://cloud.githubusercontent.com/assets/11977741/11482452/da7e044a-9770-11e5-9c31-c55bce3b3898.png)

**51 Newlines**
Collapsed
![image](https://cloud.githubusercontent.com/assets/11977741/11482468/f1dea766-9770-11e5-9863-5a588ddb1c6f.png)

Expanded
![image](https://cloud.githubusercontent.com/assets/11977741/11482472/fc6ef15e-9770-11e5-9d30-092c65af5312.png)

**Comment by Blackbaud-PaulCrowder** [comment]
We can certainly make it configurable.  However, is it really practical to show text with 50 newline characters inside a half-page-width tile?  I'm assuming the real-world example is more than just one character per line followed by a newline character and instead has wrapping text which would make for an extremely long page once expanded.  Wouldn't this make more sense to show in a modal dialog?  @Blackbaud-ToddRoberts, do we need to look into defining a pattern and adding a feature to the `bbTextExpand` directive that pops up a modal for extremely large amounts of text?

**Comment by Blackbaud-ToddRoberts** [comment]
I would much rather have very long content open in a modal than inline. Would we be able to automatically trigger showing inline vs modal based on content length?

**Comment by Blackbaud-PaulCrowder** [comment]
Yes, we can do that.

**Comment by Blackbaud-PatrickOFriel** [comment]
Confirming with @Blackbaud-ToddRoberts, we want to pop up a modal for extremely large amount of text? And do we have an idea for what we consider extremely large? and should we make that configurable as well?

**Comment by Blackbaud-ToddRoberts** [comment]
Yes we should do the modal for large text. I don't think it should be configurable, although it may need to be different for desktop vs mobile (anyone have thoughts on that?).

How do we determine content length? Is it by # of characters or # of lines? I think we would want a modal for anything where the expanded content is 2x as much as the max collapsed content. E.g. if we show 3 lines collapsed, anything with > 6 lines would expand in a modal.

**Comment by Blackbaud-PatrickOFriel** [comment]
Right now, we have the following conditions for bb-text-expand:
-  For the collapsed view, no more than 1 newline (\n) character or 200 other characters will be shown (The 200 character limit is configurable)
- For the expanded view, no more than 50 newline (\n) characters or 6500 other characters will be shown (The 6500 character limit is configurable)

So I guess the answer is that it is a combination of both characters and # of lines

**Comment by Blackbaud-PatrickOFriel** [comment]
Hey @Blackbaud-ToddRoberts, here's a plunker that opens what my current see more modal looks like. Anything that needs to be changed here? Add a header, change footer buttons, change modal size, ect? http://plnkr.co/edit/0bSUZGG8GiZgUR0nxXib?p=preview

**Comment by Blackbaud-ToddRoberts** [comment]
It's useful to have a header that can display a title, e.g. the date of a note or something. This will help preserve the user's context since they won't be able to see the surrounding info anymore.

For size, if it is configurable now we can leave it that way, assuming we default in the numbers you stated? I would say >2 newlines or 600 characters as a default to use the modal.

**Comment by Blackbaud-PatrickOFriel** [comment]
Should we show a default modal title if they don't provide anything? Like 'Expanded view' or 'See more'? Or should we leave off the modal header entirely if they don't provide a title? 

For the size, I meant the default width of the modal, which could be smaller if you preferred. And just to make sure, you're saying the see more should open a modal rather than expanding inline if the full text has more that 2 newlines or 600 characters, correct?

**Comment by Blackbaud-ToddRoberts** [comment]
For pure text displays like this we should try to keep width in the 70-90 character range, this gives us about 95 with 13px font. How is the width being determined? A flat number, or based on the grid system (e.g. 3-col or whatever)? It'd be good if we could make it ~10% narrower.

We can have a default header say "Expanded view" to provide some consistency. Can we have the X in the right side of the header to close the modal as well? I know it is redundant with the close link, but people tend to check in both places for a close mechanism.

And yes, default should be to open a modal instead of inline for >2 newlines or 600 characters.

**Comment by Blackbaud-PatrickOFriel** [comment]
The size of the modal can be configured based on a sm, md, lg scale, where sm is 300px, md is 600px, and lg is 900px. In small screen mode, all three sizes will just take up the available space.

We can definitely provide the x in the right side of the header.

**Comment by Blackbaud-ToddRoberts** [comment]
Ok, width is fine as it is then. Small would be too small.

**Comment by Blackbaud-PatrickOFriel** [comment]
Awesome, I'll get on it

**Comment by Blackbaud-PatrickOFriel** [comment]
In [v1.5.0](https://github.com/blackbaud/skyux/releases/tag/v1.5.0)
